from dataclasses import dataclass


@dataclass(frozen=True)
class PermissionDefinition:
    code: str
    label: str
    module: str
    description: str


DEFAULT_ROLES = {
    "admin": {
        "label": "Administrador",
        "description": "Acesso total ao sistema.",
    },
    "technician": {
        "label": "Técnico",
        "description": "Atendimento técnico, chamados, OS e monitoramento.",
    },
    "seller": {
        "label": "Vendedor",
        "description": "Clientes, produtos, estoque, orcamentos e vendas futuras.",
    },
    "cashier": {
        "label": "Operador de caixa",
        "description": "Acesso focado em operar o PDV e registrar vendas.",
    },
    "client": {
        "label": "Cliente",
        "description": "Acesso limitado aos próprios dados.",
    },
}

PERMISSIONS = [
    PermissionDefinition("clients:view", "Ver clientes", "clients", "Visualizar clientes."),
    PermissionDefinition("clients:create", "Criar clientes", "clients", "Cadastrar clientes."),
    PermissionDefinition("clients:update", "Editar clientes", "clients", "Alterar clientes."),
    PermissionDefinition("clients:delete", "Excluir clientes", "clients", "Excluir clientes."),
    PermissionDefinition("equipments:view", "Ver equipamentos", "equipments", "Visualizar equipamentos."),
    PermissionDefinition("equipments:create", "Criar equipamentos", "equipments", "Cadastrar equipamentos."),
    PermissionDefinition("equipments:update", "Editar equipamentos", "equipments", "Alterar equipamentos."),
    PermissionDefinition("equipments:delete", "Excluir equipamentos", "equipments", "Excluir equipamentos."),
    PermissionDefinition("tickets:view", "Ver chamados", "tickets", "Visualizar chamados."),
    PermissionDefinition("tickets:create", "Criar chamados", "tickets", "Abrir chamados."),
    PermissionDefinition("tickets:update", "Editar chamados", "tickets", "Alterar chamados."),
    PermissionDefinition("tickets:finish", "Finalizar chamados", "tickets", "Concluir ou cancelar chamados."),
    PermissionDefinition("products:view", "Ver produtos", "products", "Visualizar produtos, peças e serviços."),
    PermissionDefinition("products:create", "Criar produtos", "products", "Cadastrar produtos, peças e serviços."),
    PermissionDefinition("products:update", "Editar produtos", "products", "Alterar produtos, peças e serviços."),
    PermissionDefinition("products:delete", "Excluir produtos", "products", "Excluir produtos, peças e serviços."),
    PermissionDefinition("stock:view", "Ver estoque", "stock", "Visualizar estoque."),
    PermissionDefinition("stock:move", "Movimentar estoque", "stock", "Movimentar estoque."),
    PermissionDefinition(
        "app:access",
        "Acessar aplicativo movel",
        "stock",
        "Permite entrar no app Android/iOS da Lyncar.",
    ),
    PermissionDefinition(
        "stock:withdraw",
        "Realizar baixas de estoque",
        "stock_withdrawals",
        "Dar baixa por perda, consumo, vencimento e outros motivos.",
    ),
    PermissionDefinition("stock:entries:view", "Ver entradas", "stock_entries", "Visualizar entradas e conferências de mercadoria."),
    PermissionDefinition("stock:entries:create", "Criar entradas", "stock_entries", "Criar entradas manuais ou por XML."),
    PermissionDefinition("stock:entries:confirm", "Confirmar conferência", "stock_entries", "Confirmar conferência e movimentar estoque."),
    PermissionDefinition("stock:entries:return", "Marcar devolução", "stock_entries", "Marcar itens para devolução ao fornecedor."),
    PermissionDefinition("stock:entries:create_product_from_xml", "Cadastrar produto pelo XML", "stock_entries", "Criar produto a partir de item da NF-e."),
    PermissionDefinition("stock:batches:view", "Ver lotes", "stock", "Visualizar saldo por lote e validade."),
    PermissionDefinition("suppliers:view", "Ver fornecedores", "suppliers", "Visualizar fornecedores."),
    PermissionDefinition("suppliers:create", "Criar fornecedores", "suppliers", "Cadastrar fornecedores."),
    PermissionDefinition("suppliers:update", "Editar fornecedores", "suppliers", "Alterar fornecedores."),
    PermissionDefinition("suppliers:delete", "Excluir fornecedores", "suppliers", "Excluir fornecedores cadastrados por engano."),
    PermissionDefinition("production:view", "Ver produção", "production", "Visualizar ordens de produção."),
    PermissionDefinition("production:create", "Criar produção", "production", "Criar ordens de produção e baixar insumos."),
    PermissionDefinition(
        "service_contracts:view",
        "Ver contratos variáveis",
        "service_contracts",
        "Visualizar contratos recorrentes por apontamento.",
    ),
    PermissionDefinition(
        "service_contracts:manage",
        "Gerenciar contratos variáveis",
        "service_contracts",
        "Criar e editar contratos, regras, feriados e produtos vinculados.",
    ),
    PermissionDefinition(
        "service_contracts:appointments",
        "Apontar atendimentos",
        "service_contracts",
        "Gerar, editar, confirmar e cancelar apontamentos diários.",
    ),
    PermissionDefinition(
        "service_contracts:billing",
        "Fechar contratos variáveis",
        "service_contracts",
        "Gerar fechamento quinzenal e contas a receber.",
    ),
    PermissionDefinition("sales:view", "Ver vendas", "sales", "Visualizar vendas e historico comercial."),
    PermissionDefinition("sales:create", "Operar PDV", "pdv", "Abrir o PDV, registrar vendas e receber pagamentos."),
    PermissionDefinition("sales:cancel", "Cancelar vendas", "sales", "Cancelar vendas e estornar estoque."),
    PermissionDefinition(
        "cash_closings:manage",
        "Conferir caixa e tesouraria",
        "cash_closings",
        "Aprovar, corrigir e marcar divergencias nos fechamentos de caixa.",
    ),
    PermissionDefinition("pdv_operators:manage", "Administrar PDV Windows", "pdv_windows", "Criar operadores, fiscais e terminais do aplicativo Windows."),
    PermissionDefinition("service_orders:view", "Ver OS", "service_orders", "Visualizar ordens de serviço."),
    PermissionDefinition("service_orders:create", "Criar OS", "service_orders", "Abrir ordens de serviço."),
    PermissionDefinition("service_orders:update", "Editar OS", "service_orders", "Alterar ordens de serviço."),
    PermissionDefinition("service_orders:finish", "Finalizar OS", "service_orders", "Concluir ou cancelar OS."),
    PermissionDefinition("monitoring:view", "Ver monitoramento", "monitoring", "Visualizar monitoramento."),
    PermissionDefinition("monitoring:write", "Enviar monitoramento", "monitoring", "Registrar dados do agente."),
    PermissionDefinition("dashboard:view", "Ver dashboard", "dashboard", "Visualizar dashboard."),
    PermissionDefinition("reports:view", "Ver relatórios", "reports", "Visualizar relatórios."),
    PermissionDefinition("finance:view", "Ver financeiro", "finance", "Visualizar financeiro."),
    PermissionDefinition(
        "finance:receivables:view",
        "Ver contas a receber",
        "finance",
        "Visualizar contas a receber por cliente.",
    ),
    PermissionDefinition(
        "finance:receivables:pay",
        "Baixar contas a receber",
        "finance",
        "Registrar recebimentos totais ou parciais.",
    ),
    PermissionDefinition(
        "finance:payables:view",
        "Ver contas a pagar",
        "finance",
        "Visualizar contas a pagar de fornecedores.",
    ),
    PermissionDefinition(
        "finance:payables:manage",
        "Gerenciar contas a pagar",
        "finance",
        "Criar, alterar e baixar contas a pagar.",
    ),
    PermissionDefinition("fiscal:view", "Ver fiscal", "fiscal", "Visualizar configuração e documentos fiscais."),
    PermissionDefinition("fiscal:settings", "Configurar fiscal", "fiscal", "Alterar configuração fiscal e certificado A1."),
    PermissionDefinition("fiscal:emit", "Preparar/emitar fiscal", "fiscal", "Preparar emissão de NFC-e/NF-e."),
    PermissionDefinition("fiscal:cancel", "Cancelar documento fiscal", "fiscal", "Transmitir evento real de cancelamento para a SEFAZ."),
    PermissionDefinition("fiscal:documents:view", "Ver documentos fiscais", "fiscal", "Visualizar documentos fiscais e XMLs."),
    PermissionDefinition("users:manage", "Administrar usuários", "users", "Criar e alterar usuários."),
    PermissionDefinition("permissions:manage", "Administrar permissões", "permissions", "Gerenciar permissões."),
]

ROLE_PERMISSION_CODES = {
    "admin": [permission.code for permission in PERMISSIONS],
    "technician": [
        "clients:view",
        "equipments:view",
        "equipments:update",
        "tickets:view",
        "tickets:create",
        "tickets:update",
        "tickets:finish",
        "service_orders:view",
        "service_orders:create",
        "service_orders:update",
        "service_orders:finish",
        "monitoring:view",
        "monitoring:write",
        "dashboard:view",
    ],
    "seller": [
        "clients:view",
        "clients:create",
        "clients:update",
        "products:view",
        "products:create",
        "products:update",
        "stock:view",
        "stock:entries:view",
        "stock:entries:create",
        "stock:entries:confirm",
        "stock:entries:create_product_from_xml",
        "stock:batches:view",
        "suppliers:view",
        "suppliers:create",
        "suppliers:update",
        "suppliers:delete",
        "production:view",
        "production:create",
        "service_contracts:view",
        "service_contracts:manage",
        "service_contracts:appointments",
        "service_contracts:billing",
        "sales:view",
        "sales:create",
        "sales:cancel",
        "pdv_operators:manage",
        "service_orders:view",
        "service_orders:create",
        "dashboard:view",
        "reports:view",
        "finance:view",
        "finance:receivables:view",
        "finance:receivables:pay",
        "finance:payables:view",
        "fiscal:view",
        "fiscal:documents:view",
    ],
    "cashier": [
        "clients:view",
        "products:view",
        "stock:view",
        "stock:batches:view",
        "sales:create",
        "dashboard:view",
        "fiscal:view",
        "fiscal:documents:view",
    ],
    "client": [
        "tickets:view",
        "tickets:create",
        "service_orders:view",
        "equipments:view",
        "monitoring:view",
    ],
}
